// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-zero-box/app/internal/command"
	demo2 "go-zero-box/app/internal/command/demo"
	"go-zero-box/app/internal/config"
	"go-zero-box/app/internal/middleware"
	"go-zero-box/app/internal/model"
	"go-zero-box/app/internal/model/messagemodel"
	"go-zero-box/app/internal/model/usermodel"
	"go-zero-box/app/internal/pkg"
	"go-zero-box/app/internal/pkg/database"
	"go-zero-box/app/internal/pkg/redis"
	"go-zero-box/app/internal/queue"
	message2 "go-zero-box/app/internal/queue/message"
	"go-zero-box/app/internal/services"
	"go-zero-box/app/internal/services/demo"
	"go-zero-box/app/internal/services/message"
	"go-zero-box/app/internal/svc"
)

// Injectors from wire.go:

func initApp(c *config.Config) *App {
	redisConfig := c.Redis
	redisDefault := redis.NewDefault(redisConfig)
	databaseConfig := c.Database
	databaseDefault := database.NewDefault(databaseConfig)
	userModel := usermodel.NewUserModel(databaseDefault)
	messageModel := messagemodel.NewMessageModel(databaseDefault)
	modelModel := model.NewModel(userModel, messageModel)
	service := demo.NewService(userModel)
	messageService := message.NewService()
	servicesServices := services.NewServices(service, messageService)
	authMiddleware := middleware.NewAuthMiddleware(c)
	middlewareMiddleware := middleware.NewMiddleware(authMiddleware)
	serviceContext := svc.NewServiceContext(redisDefault, c, modelModel, servicesServices, middlewareMiddleware)
	mailQueue := message2.NewMailQueue(messageService)
	smsQueue := message2.NewSmsQueue(messageService)
	wechatQueue := message2.NewWechatQueue(messageService)
	queueQueue := queue.NewQueue(mailQueue, smsQueue, wechatQueue)
	personProcess := demo2.NewPersonProcess()
	commandCommand := command.NewCommand(personProcess)
	pkgPkg := pkg.NewPkg(databaseDefault, redisDefault)
	app := NewApp(c, serviceContext, queueQueue, commandCommand, pkgPkg)
	return app
}

// wire.go:

type App struct {
	config  *config.Config
	svcCtx  *svc.ServiceContext
	queue   *queue.Queue
	command *command.Command
	pkg     *pkg.Pkg
}

func NewApp(config2 *config.Config, svcCtx *svc.ServiceContext, queue2 *queue.Queue, command2 *command.Command, pkg2 *pkg.Pkg) *App {
	return &App{config: config2, svcCtx: svcCtx, queue: queue2, command: command2, pkg: pkg2}
}
