// Code generated by goctl. DO NOT EDIT.
package types

type ExitData struct {
	Url string `json:"url"`
}

type ExitReq struct {
}

type ExitResp struct {
	Response
	Data ExitData `json:"data"`
}

type HelloData struct {
}

type HelloReq struct {
}

type HelloResp struct {
	Response
	Data HelloData `json:"data"`
}

type LoginData struct {
	User  LoginDataUser `json:"user"`  //用户基本信息
	Token string        `json:"token"` //服务端返回的token值
}

type LoginDataUser struct {
	ID       uint64 `json:"id"`       // 账号ID
	NickName string `json:"nickname"` //昵称
}

type LoginReq struct {
	Account  string `json:"account,example=admin"`
	Password string `json:"password,example=123456"`
}

type LoginResp struct {
	Response
	Data LoginData `json:"data"`
}

type Paginate struct {
	Page     uint64 `form:"page,optional,default=1,range=[1:]"` // 页码
	PageSize uint64 `form:"page_size,optional,default=10"`      // 分页大小
}

type PaginateResp struct {
	Page     uint64 `json:"page"`      // 页码
	PageSize uint64 `json:"page_size"` // 分页大小
	Total    int64  `json:"total"`     // 总条数
}

type RegisterReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Response
}

type Response struct {
	Code    int    `json:"code"`    // 返回状态0-成功<br>10001-默认异常错误码,前端可提示<br>20001-系统异常错误码，前端可不提示<br>40000-未登录状态码
	Message string `json:"message"` // 返回信息
}

type SwaggerReq struct {
}

type SwaggerResp struct {
	Response
}

type UserInfoData struct {
	Id        uint64 `json:"id"`
	Account   string `json:"account"`    // 用户名
	Name      string `json:"name"`       // 姓名
	JobNumber string `json:"job_number"` // 工号
	Email     string `json:"email"`      // 邮箱
	Note      string `json:"note"`       // 备注
	Status    uint64 `json:"status"`     // 状态 1启动 2禁用
	IsDelete  int64  `json:"is_delete"`  // 是否删除 1是 2否
}

type UserInfoResp struct {
	Response
	Data *UserInfoData `json:"data"`
}
