// Code generated by goctl. DO NOT EDIT.
package types

type AuthResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message,default=ok"`
}

type ExitData struct {
	Url string `json:"url"`
}

type ExitReq struct {
}

type ExitResp struct {
	UserResponse
	Data ExitData `json:"data"`
}

type HelloData struct {
}

type HelloReq struct {
}

type HelloResp struct {
	HelloResponse
	Data HelloData `json:"data"`
}

type HelloResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type LoginData struct {
	User  LoginDataUser `json:"user"`  //用户基本信息
	Token string        `json:"token"` //服务端返回的token值
}

type LoginDataUser struct {
	ID       int64  `json:"id"`       // 账号ID
	NickName string `json:"nickname"` //昵称
}

type LoginReq struct {
	Account  string `json:"account,example=admin"`
	Password string `json:"password,example=123456"`
}

type LoginResp struct {
	AuthResponse
	Data LoginData `json:"data"`
}

type RegisterReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type RegisterResp struct {
	AuthResponse
}

type SwaggerData struct {
}

type SwaggerReq struct {
}

type SwaggerResp struct {
	SwaggerResponse
	Data SwaggerData `json:"data"`
}

type SwaggerResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type UserInfoData struct {
	Id        int64  `json:"id"`
	Account   string `json:"account"`    // 用户名
	Name      string `json:"name"`       // 姓名
	JobNumber string `json:"job_number"` // 工号
	Email     string `json:"email"`      // 邮箱
	Note      string `json:"note"`       // 备注
	Status    int64  `json:"status"`     // 状态 1启动 2禁用
	IsDelete  int64  `json:"is_delete"`  // 是否删除 1是 2否
}

type UserInfoResp struct {
	UserResponse
	Data *UserInfoData `json:"data"`
}

type UserPaginate struct {
	Page     uint64 `form:"page,optional,default=1,range=[1:]"` // 页码
	PageSize uint64 `form:"page_size,optional,default=10"`      // 分页大小
}

type UserPaginateResp struct {
	Page     uint64 `json:"page"`      // 页码
	PageSize uint64 `json:"page_size"` // 分页大小
	Total    int64  `json:"total"`     // 总条数
}

type UserResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
